branches:
  - main
  - name: dev
    prerelease: true
debug: true
ci: true
dryRun: false
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - "@semantic-release/changelog"
  - "@semantic-release/npm"
  - "@semantic-release/git"
  - "@semantic-release/github"
