# CONFIG ---------------------------------
name: CI
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
# PIPELINE ---------------------------------
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v3
      # set Node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      # build --------
      - name: Install deps
        run: npm ci
      # test --------
      - name: test
        run: npm run test -- --browsers=ChromeHeadless
      # linter --------
      - name: lint
        run: npm run eslint
      #transpilation --------
      - name: compile
        run: npm run compile
      #release --------
      - name: release
        run: npm run release
